project: Thesis
name: Skip Attention

parameters:
    model name: 'MultiScaleSkipAttentionWithSmoothness'
    model class: 'SkipAttentionModel'
    encoder type: 'base'

    multiscale: True
    smoothness loss: True
    lambda l1: 0.9
    lambda smooth: 0.1
    
    batch size: 8
    lr: 0.0001
    monitor: 'val_loss_total'
    epochs: 12