project: Thesis
name: Skip Attention

parameters:
    model name: 'MultiScaleSkipAttention'
    model class: 'SkipAttentionModel'
    multiscale: True
    batch size: 4
    lr: 0.0001
    monitor: 'val_l1_depth_loss'
    epochs': 8